name = "wearther"
account_id = "5d1e8733fafc56dc67c31661af212d57"
workers_dev = true
compatibility_date = "2024-08-19"

main = "worker.js"

[site]
bucket = "./dist"

routes = [
  { pattern = "marcoczirpek.com/app/wearther*", zone_name = "marcoczirpek.com" }
]